version: "3.8"

services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-abhipreet}"
    image: cybulde-data-processing
    container_name: cybulde-data-processing-container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-abhipreet}"
        USER_ID : "${USER_ID:-1000}"
    volumes:
      # mount to test locally, else we copy this folder in the Dockerfile
      #- ./:/app/
      - /home/abhipreet/.config/gcloud:/home/${USER_NAME:-abhipreet}/.config/gcloud
