defaults:
  - dataset_reader_manager_schema
  - dataset_reader@dataset_readers.ghc: ghc
  - dataset_reader@dataset_readers.jigsaw: jigsaw
  - dataset_reader@dataset_readers.twitter: twitter

available_memory: null
