defaults:
  - data_processing_config_schema
  - dask_cluster: gcp_dask_cluster
  - dataset_reader_manager: ghc_jigsaw_twitter
  - dataset_cleaner_manager: dataset_cleaner


version: v9
fetch_data: false
processed_data_save_dir: gs://cybulde-data-store/data/processed
